### ISSUE TITLE
Function returning error

### ISSUE THREAD

**Issue by JamesRLamar** [carlrobert/Hello-ScriptCraft#1]
I love the work you've done BTW. I don't know if this is an artifact of some change that has been made in the core ScriptCraft, but I have to make a small change on the first line for this function to work correctly.

So 'var Drone = require('../drone/drone').Drone; '
instead of 'var Drone = require('../drone').Drone;'

I see the former syntax in other examples on the ScriptCraft websites as well.

**Comment by carlrobert** [comment]
New syntax: 
var Drone = require('drone');
